<div class="jumbotron">
    <h1><?php echo sprintf('StartAix') ?></h1>
    <p><?php echo sprintf('Le site des startup d\'Ynov Aix.') ?></p>
    <p><a class="btn btn-success btn-lg" href="#" target="_blank"><?php echo ('En savoir plus ') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo ('Startup 1') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf('Description startup...') ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo ('Plus d\'infos') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo ('Startup 2') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf('Description startup...') ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo ('Plus d\'infos') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo ('Startup 3') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf('Description startup...') ?></p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?php echo ('Plus d\'infos') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
